# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 808fca12f8a466e8f9929889b83ded12fbca7456448ccf6111155aa072eadd4de5c54f45cd82ba19ea279b7266fe8db694c04c44382c8b3a646030697302ada4

test:
  secret_key_base: 7edad64ab90a437a3ee5ec404c64a557a789e09c850bf6151b22fb55c4a7fc91747d98e8ea1f6b9b092b76515de9433c85427db5c04529ab8fee69b465095768

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
